name: Astronomer CI - Deploy code to main Deployment

on:
  push:
    branches:
      - main

env:
  ## Set your API token as a GitHub secret
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy code to main Deployment
      uses: astronomer/deploy-action@v0.4
      with:
        deployment-id: clschfn9n24939050wqf594c4pj
